# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/IndentationConsistency:
  Enabled: false
  EnforcedStyle: normal
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/IndentationWidth:
  Enabled: true
Layout/LineLength:
  Max: 80
