# Omakase Ruby styling for Rails
plugins:
  - rubocop-rspec

inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/IndentationConsistency:
  Enabled: false
  EnforcedStyle: normal
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/IndentationWidth:
  Enabled: true
Layout/LineLength:
  Max: 80

# RSpec
RSpec/MultipleExpectations:
  Max: 3
